### ISSUE TITLE
 Failed to execute script 'koboldcpp' due to unhandled exception!

### ISSUE THREAD

**Issue by Lordbl4** [LostRuins/koboldcpp#56] opened 2023-04-13 17:51 UTC
win11, Intel(R) Xeon(R) CPU X3470, 16gb ram, koboldcpp 1.6, model - Vicuna 13B

```
F:\koboldcpp>koboldcpp.exe --noavx2 --noblas ggml-model-q4_0.bin
Welcome to KoboldCpp - Version 1.6
Attempting to use non-avx2 compatibility library without OpenBLAS.
Initializing dynamic library: koboldcpp_noavx2.dll
Loading model: F:\koboldcpp\ggml-model-q4_0.bin
[Parts: 1, Threads: 3]


Identified as LLAMA model: (ver 3)
Attempting to Load...

System Info: AVX = 1 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from F:\koboldcpp\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 439, in <module>
  File "koboldcpp.py", line 387, in main
  File "koboldcpp.py", line 81, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[13096] Failed to execute script 'koboldcpp' due to unhandled exception!
```

**Comment by Moscowman** [comment] 2023-04-13 18:56
I have the same problem on CPU with AVX

**Comment by Lordbl4** [comment] 2023-04-13 19:09
> You CPU don't have AVX2 instruction?

yep
![YXdetAJ 1](https://user-images.githubusercontent.com/5826558/231859278-cc7e30ca-b3c3-4299-8a48-2d8d11f8ecec.png)

**Comment by LostRuins** [comment] 2023-04-14 02:13
@Moscowman , you are not using `--noavx2` yet. I can see the library being loaded.

@Lordbl4 For you I am not sure, can you try running using `--nommap` in addition to `--noavx2` as well?

**Comment by Lordbl4** [comment] 2023-04-14 03:55
> @Lordbl4 For you I am not sure, can you try running using `--nommap` in addition to `--noavx2` as well?
same error. do I need to install any additional libraries for windows?

`F:\koboldcpp>koboldcpp.exe --noavx2 --noblas --nommap ggml-model-q4_0.bin
Welcome to KoboldCpp - Version 1.6
Attempting to use non-avx2 compatibility library without OpenBLAS.
Initializing dynamic library: koboldcpp_noavx2.dll
Loading model: F:\koboldcpp\ggml-model-q4_0.bin
[Parts: 1, Threads: 3]


Identified as LLAMA model: (ver 3)
Attempting to Load...

System Info: AVX = 1 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from F:\koboldcpp\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size = 7945699.98 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 439, in <module>
  File "koboldcpp.py", line 387, in main
  File "koboldcpp.py", line 81, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[9664] Failed to execute script 'koboldcpp' due to unhandled exception!`

**Comment by LostRuins** [comment] 2023-04-14 05:11
Hm yeah, but without any accelerators I think it will be hideously slow. 

If there is enough demand I might add that to the library build list, but I do want to avoid cluttering the build with too many different configurations. Alternatively like @na-na-hi suggested you can trigger the build with the native flags which should make a build specially for that CPU configuration.

**Comment by Moscowman** [comment] 2023-04-14 08:08
> @Moscowman , you are not using `--noavx2` yet. I can see the library being loaded.
> 
> @Lordbl4 For you I am not sure, can you try running using `--nommap` in addition to `--noavx2` as well?

Yes, I am not using "--noavx2" because my CPU DOES have avx2 support, but the error is the same.

**Comment by mrdc** [comment] 2023-04-14 08:09
> If there is enough demand I might add that to the library build list

I can build no avx version if somebody needs it. Do I need to install visual studio for building? I use *nix for building 100% of my c/c++ code, so have little idea about building it in Windows)

**Comment by gustrd** [comment] 2023-04-14 12:19
I tried to build with w64devkit, but I receive the following error:

PS ***@***.***> make
I llama.cpp build info:
I UNAME_S:  Windows_NT
I UNAME_P:  unknown
I UNAME_M:  i686
I CFLAGS:   -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s
 -mavx
I CXXFLAGS: -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar
I LDFLAGS:
I CC:       cc (GCC) 12.2.0
I CXX:      g++.exe (GCC) 12.2.0

cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -mf16c  -mavx2 -msse3 -mfma  -c ggml.c -o ggml.o
cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -mf16c  -mavx2 -msse3 -mfma  -c otherarch/ggml_v1.c -o ggml_v1.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c expose.cpp -o expose.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c examples/common.cpp -o common.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c llama_adapter.cpp -o llama_adapter.o
In file included from llama.cpp:6,
                 from llamaextra.cpp:3,
                 from llama_adapter.cpp:21:
llama_util.h: In constructor 'llama_mmap::llama_mmap(llama_file*)':
llama_util.h:224:94: note: '#pragma message: warning: You are building for
pre-Windows 8; prefetch not supported'
  224 |         #pragma message("warning: You are building for pre-Windows
8; prefetch not supported")
      |
                         ^
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c gpttype_adapter.cpp -o gpttype_adapter.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar  ggml.o ggml_v1.o expose.o common.o llama_adapter.o
gpttype_adapter.o -shared -o koboldcpp.dll
cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -c ggml.c -o ggml_noavx2.o
cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -mf16c  -c otherarch/ggml_v1.c -o ggml_v1_noavx2.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar ggml_noavx2.o ggml_v1_noavx2.o expose.o common.o
llama_adapter.o gpttype_adapter.o -shared -o koboldcpp_noavx2.dll
cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -mf16c  -mavx2 -msse3 -mfma  -DGGML_USE_OPENBLAS -c ggml.c -o
ggml_openblas.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar ggml_openblas.o ggml_v1.o expose.o common.o llama_adapter.o
gpttype_adapter.o lib/libopenblas.lib -shared -o koboldcpp_openblas.dll
***@***.***\bin/ld.exe: ggml_openblas.o:ggml.c:(.text+0x91b7): undefined
reference to `cblas_sgemm'
***@***.***\bin/ld.exe: ggml_openblas.o:ggml.c:(.text+0x15d53): undefined
reference to `cblas_sgemm'
***@***.***\bin/ld.exe: ggml_openblas.o:ggml.c:(.text+0x17fca): undefined
reference to `cblas_sgemm'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:224: llamalib_openblas] Error 1

I used the kit at:

https://github.com/skeeto/w64devkit

I could build it with no problem at ubuntu.

Am I doing something wrong?

Em sex., 14 de abr. de 2023 às 05:10, mrdc ***@***.***>
escreveu:

**Comment by LostRuins** [comment] 2023-04-14 12:29
Looks to me like you don't have the cblas headers for some reason

**Comment by gustrd** [comment] 2023-04-14 13:34
Even adding #include <cblas.h> at ggml.c or ggml.h doesn't work.

Strange that at Linux it works well, I just have this problem at Windows.

Any other ideas?


Em sex., 14 de abr. de 2023 às 09:29, LostRuins ***@***.***>
escreveu:

**Comment by LostRuins** [comment] 2023-04-14 13:56
For some reason, there are still issues with openblas.

How about this, pull the latest version, and run this make command instead: `make simple`

This skips the included blas libraries and just builds the base versions. You can see if that works first and run the base non blas version.

Later, after that is working, you can try linking the libraries with your local install instead with `make simple LLAMA_OPENBLAS=1`

**Comment by gustrd** [comment] 2023-04-14 15:11
I tried both with CBLAST and "make simple", both gave me error:

PS ***@***.***> make LLAMA_CLBLAST=1
I llama.cpp build info:
I UNAME_S:  Windows_NT
I UNAME_P:  unknown
I UNAME_M:  i686
I CFLAGS:   -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s
 -mavx  -DGGML_USE_CLBLAST -DGGML_USE_OPENBLASI CXXFLAGS: -I. -I./examples
-Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s -Wno-multichar
I LDFLAGS:  -lclblast -lOpenCL
I CC:       cc (GCC) 12.2.0
I CXX:      g++ (GCC) 12.2.0

cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -DGGML_USE_CLBLAST -DGGML_USE_OPENBLAS -mf16c  -mavx2 -msse3 -mfma  -c
ggml.c -o ggml.o
cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -DGGML_USE_CLBLAST -DGGML_USE_OPENBLAS -mf16c  -mavx2 -msse3 -mfma  -c
otherarch/ggml_v1.c -o ggml_v1.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c expose.cpp -o expose.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c examples/common.cpp -o common.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c llama_adapter.cpp -o llama_adapter.o
In file included from llama.cpp:6,
                 from llamaextra.cpp:3,
                 from llama_adapter.cpp:21:
llama_util.h: In constructor 'llama_mmap::llama_mmap(llama_file*)':
llama_util.h:224:94: note: '#pragma message: warning: You are building for
pre-Windows 8; prefetch not supported'
  224 |         #pragma message("warning: You are building for pre-Windows
8; prefetch not supported")
      |
                               ^
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c gpttype_adapter.cpp -o gpttype_adapter.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar  ggml.o ggml_v1.o expose.o common.o llama_adapter.o
gpttype_adapter.o -shared -o koboldcpp.dll -lclblast -lOpenCL
***@***.***\bin/ld.exe: cannot find -lclblast: No such file or directory
***@***.***\bin/ld.exe: cannot find -lOpenCL: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:221: llamalib] Error 1

___  -----------------------------------------------___


PS ***@***.***> make simple
I llama.cpp build info:
I UNAME_S:  Windows_NT
I UNAME_P:  unknown
I UNAME_M:  i686
I CFLAGS:   -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s
 -mavx
I CXXFLAGS: -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar
I LDFLAGS:
I CC:       cc (GCC) 12.2.0
I CXX:      g++ (GCC) 12.2.0

make: *** No rule to make target 'simple'.  Stop.



Em sex., 14 de abr. de 2023 às 10:56, LostRuins ***@***.***>
escreveu:

**Comment by LostRuins** [comment] 2023-04-14 15:21
Can you post your log of the output `make simple` without any other flags?

**Comment by gustrd** [comment] 2023-04-14 15:22
I just did at at commit 1b1c073:

PS ***@***.***> make simple
I llama.cpp build info:
I UNAME_S:  Windows_NT
I UNAME_P:  unknown
I UNAME_M:  i686
I CFLAGS:   -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s
 -mavx
I CXXFLAGS: -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar
I LDFLAGS:
I CC:       cc (GCC) 12.2.0
I CXX:      g++ (GCC) 12.2.0

cc  -I.              -Ofast -DNDEBUG -std=c11   -fPIC -pthread -s  -mavx
 -mf16c  -mavx2 -msse3 -mfma  -c ggml.c -o ggml.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c expose.cpp -o expose.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar -c examples/common.cpp -o common.o
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s
-Wno-multichar  ggml.o ggml_v1.o expose.o common.o llama_adapter.o
gpttype_adapter.o -shared -o koboldcpp.dll
***@***.***\bin/ld.exe: ggml_v1.o:ggml_v1.c:(.text+0x5cc9): undefined
reference to `cblas_sgemm'
***@***.***\bin/ld.exe: ggml_v1.o:ggml_v1.c:(.text+0xa633): undefined
reference to `cblas_sgemm'
***@***.***\bin/ld.exe: ggml_v1.o:ggml_v1.c:(.text+0xd161): undefined
reference to `cblas_sgemm'
***@***.***\bin/ld.exe: ggml_v1.o:ggml_v1.c:(.text+0xe7f0): undefined
reference to `cblas_sgemm'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:223: llamalib] Error 1



Em sex., 14 de abr. de 2023 às 12:21, LostRuins ***@***.***>
escreveu:

**Comment by LostRuins** [comment] 2023-04-14 15:33
That is odd. Are you defining the environment variables `GGML_USE_ACCELERATE` or `GGML_USE_OPENBLAS` somewhere else? because if you don't build with those it should not even have that function definition.

**Comment by gustrd** [comment] 2023-04-14 15:49
It doesn't look so. I used the "set" command at Command Prompt and there is
no variable starting at GGML.

Em sex., 14 de abr. de 2023 às 12:33, LostRuins ***@***.***>
escreveu:

**Comment by mrdc** [comment] 2023-04-14 16:15
> For some reason, there are still issues with openblas.

I've built `koboldcpp_noavx2.dll` and `koboldcpp.dll` using simple target.

**Comment by mrdc** [comment] 2023-04-14 16:47
> because if you don't build with those it should not even have that function definition.

1. So, I'm emulating CPU without avx: I've placed `koboldcpp_noavx2.dll` and `koboldcpp.dll` (compiled without avx) near koboldcpp.exe and was using `--noavx2 --noblas`  args, but koboldcpp.exe crashes with the same error: `OSError: [WinError -1073741795] Windows Error 0xc000001d`
2. I've unpacked `koboldcpp.exe` to replace `koboldcpp_noavx2.dll` and `koboldcpp.dll`, which I've built without avx , but repacking it back to exe is not working :/
3. I've built main.exe without avx and was trying to lauch it directly - it silently closes:
```
main.exe --ctx_size 2048 --temp 0.7 --top_k 40 --top_p 0.5 --repeat_last_n 256 --batch_size 1024 --repeat_penalty 1.17647 --threads 4   --model .\ggml-13b-4bit-q4_0.bin  --n_predict 2048   --color --interactive   --reverse-prompt "User:"   --prompt "Text transcript of a never ending dialog, where User interacts with an AI assistant named ChatLLaMa. ChatLLaMa is helpful, kind, honest, friendly, good at writing and never fails to answer User's requests immediately and with details and precision. There are no annotations like (30 seconds passed...) or (to himself), just what User and ChatLLaMa say aloud to each other. The dialog lasts for years, the entirety of it is shared below. It's 10000 pages long. The transcript only includes text, it does not include markup like HTML and Markdown."
main: seed = 1681490158
llama.cpp: loading model from .\ggml-13b-4bit-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 4 (mostly Q4_1, some F16)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
```
No errors - main silently closes after `llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)`

**Comment by mrdc** [comment] 2023-04-14 16:54
> On this CPU I have to compile with `-march=native -mtune=native` instead of the default flags for it to work.

Have you repacked koboldcpp.exe with recompiled `koboldcpp_noavx2.dll` and `koboldcpp.dll`?
I'm not sure that koboldcpp.exe is picking up these new dlls when I place them in the same folder.

**Comment by mrdc** [comment] 2023-04-15 08:13
Running koboldcpp.py directly gives this error:

```
python .\koboldcpp.py --noavx2 --noblas
Welcome to KoboldCpp - Version 1.7
Attempting to use non-avx2 compatibility library without OpenBLAS.
Initializing dynamic library: koboldcpp_noavx2.dll
Traceback (most recent call last):
  File ".\koboldcpp.py", line 442, in <module>
    main(args)
  File ".\koboldcpp.py", line 357, in main
    init_library() # Note: if blas does not exist and is enabled, program will crash.
  File ".\koboldcpp.py", line 62, in init_library
    handle = ctypes.CDLL(os.path.join(dir_path, libname ))
  File "C:\Users\xxxxxxxxxxxxx\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'F:\dev\koboldcpp-concedo\koboldcpp_noavx2.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by mrdc** [comment] 2023-04-15 08:16
I've solved the issue: it's related to some missing deps when I was building on Windows and Python ctypes used for dll loading messed with dll importing, now I can confirm that special noavx build works fine on any CPU.

**Comment by LostRuins** [comment] 2023-04-15 08:17
great. you may mark issue as closed if it's all working

**Comment by mrdc** [comment] 2023-04-15 08:18
> great. you may mark issue as closed if it's all working

Not my issue, so can't close it :)

**Comment by LostRuins** [comment] 2023-04-15 08:19
I'll wait for the poster to respond for a bit before closing

**Comment by LostRuins** [comment] 2023-04-15 08:19
i imagine your no avx build is horribly slow? what kind of speed do you get @mrdc

**Comment by mrdc** [comment] 2023-04-15 08:44
> i imagine your no avx build is horribly slow? what kind of speed do you get

Yes, it's unusable without avx & blas. Still waiting for 13b model to answer.

**Comment by Moscowman** [comment] 2023-04-15 08:50
> great. you may mark issue as closed if it's all working

Why do you think that the issue can be closed? The poster's CPU has AVX1, my CPU has AVX2, showing the same error. So, how does this issue relates to no-avx build?

**Comment by mrdc** [comment] 2023-04-15 09:04
> So, how does this issue relates to no-avx build?

Have you tried making no avx build yourself and then saying that it's not avx related? Me and the person above confirmed it. Other similar issues confirm it as well. No avx build fixes the issue.

**Comment by Moscowman** [comment] 2023-04-15 09:09
> 

If you don't use some library and this resolves some issue, it may indicate that your way of using it may be incorrect. 

Anyway, you are free to make any conclusions

**Comment by mrdc** [comment] 2023-04-15 09:15
> If you don't use some library and this resolves some issue, it may indicate that your way of using it may be incorrect.

If you are making statements without reading and understanding what we are discussing here - it's not our problem. 
It's not about lib it's about compiling with diff flags - it's totally different LOL

**Comment by Moscowman** [comment] 2023-04-15 09:20
> 

Don't you think that flags enables or disables some libs or methods or switches to another one? Or what do flags do at your opinion?

**Comment by mrdc** [comment] 2023-04-15 09:23
> Don't you think that flags enables or disables some libs or methods or switches to another one?

LOL no! It's cpp and flags are for compiler.

**Comment by Moscowman** [comment] 2023-04-15 09:36
OK, you are right.

Then I reformulate: if the error appear on my CPU with AVX1 and AVX2, does disabling it solve the issue? I think that it only masks it by dramatically decreasing performance.

By the way, Lordbl4's CPU has AVX1 with the same error.

Of cause it can be an error in cpp resulting to wrong compilation, but it's a very rare case

**Comment by LostRuins** [comment] 2023-04-15 16:09
If it works for you with `--noavx` but fails with without that flag, then of course it is related to not having AVX. 

Are you sure you actually have AVX2 support? Please try downloading HWINFO64 and checking what instructions are actually supported on  your chipset.

**Comment by jimmyhlyu** [comment] 2023-04-15 18:31
> @mrdc 
> I've solved the issue: it was related to some missing deps when I was building on Windows and Python ctypes messed with dll importing, now I can confirm that special noavx build works fine on any CPU.

How do you solve it? I am facing the same issue when building on Windows.

**Comment by ENjoyBlue2021** [comment] 2023-04-17 14:21
Hmm, I have the same issue on linux ubuntu.
How did you guys fix this?
`OSError: /media/w/PhoenixSSD/oobabooga/koboldcpp-1.9/koboldcpp.dll: undefined symbol: cblas_sgemm`
Looks like it can't find the packages.
I did apt install both libclblast-dev and libopenblas-dev. Do I need to further do something to make it work?

**Comment by gustrd** [comment] 2023-04-17 17:38
@ENjoyBlue2021 , are you sure that your folder where libopenblas is installed is the same described at the Makefile? 

ifdef LLAMA_OPENBLAS
	CFLAGS  += -DGGML_USE_OPENBLAS -I/usr/local/include/openblas
	LDFLAGS += -lopenblas
endif

Check if it is at /usr/local/include/openblas . 

If it's not the issue make sure you are running "make LLAMA_OPENBLAS=1".

**Comment by Lordbl4** [comment] 2023-04-17 20:02
now error in other lines
`F:\koboldcpp>koboldcpp.exe --noavx --noblas ggml-model-q4_0.bin
Welcome to KoboldCpp - Version 1.9
Attempting to use non-avx2 compatibility library without OpenBLAS.
Initializing dynamic library: koboldcpp_noavx2.dll
Loading model: F:\koboldcpp\ggml-model-q4_0.bin
[Parts: 1, Threads: 3, SmartContext: False]

Identified as LLAMA model: (ver 3)
Attempting to Load...

System Info: AVX = 1 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from F:\koboldcpp\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 465, in <module>
  File "koboldcpp.py", line 409, in main
  File "koboldcpp.py", line 88, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[10496] Failed to execute script 'koboldcpp' due to unhandled exception!`

**Comment by ENjoyBlue2021** [comment] 2023-04-18 01:18
@gustrd 
Thanks, make LLAMA_OPENBLAS=1 works. The error keeps appearing with make LLAMA_CLBLAST=1 though.
I did install both libclblast-dev and libopenblas-dev packages on ubuntu.

**Comment by mrdc** [comment] 2023-04-18 10:05
> How do you solve it?

Use static.

**Comment by mrdc** [comment] 2023-04-18 10:06
> now error in other lines

It won't run because `avx1` is still required. `--noavx2` disables `avx2` not `avx1`

**Comment by Ph0rk0z** [comment] 2023-04-22 18:02
have error:

```
g++ -I. -I./examples -I./include -I./include/CL -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s -Wno-multichar -pthread	 ggml_clblast.o ggml_rwkv.o ggml_v1.o expose.o common.o gpttype_adapter.o -lclblast -lOpenCL  -lopenblas -shared -o koboldcpp_clblast.so 
/usr/bin/ld: cannot find -lclblast
collect2: error: ld returned 1 exit status
make: *** [Makefile:263: koboldcpp_clblast] Error 1
```

if I do `make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1`


but if I do `make  LLAMA_OPENBLAS=1` clblast compiles anyway?

**Comment by LostRuins** [comment] 2023-04-23 03:16
if you don't include clblast it wont compile with it. Maybe you need to install some additional libraries

**Comment by Ph0rk0z** [comment] 2023-04-23 03:55
clblast.dll is still made. libclblast-dev and libopenblas-dev are both installed.

**Comment by LostRuins** [comment] 2023-04-23 05:37
are you on windows? that's a prebuilt binary. the library koboldcpp uses is called `koboldcpp_clblast.dll` or `koboldcpp_clblast.so` depending on platform.

**Comment by Ph0rk0z** [comment] 2023-04-23 11:50
I have both but I am trying to get it going proper on ubuntu. It is not building the .so for clblast. I wonder what gives.

**Comment by Ph0rk0z** [comment] 2023-04-23 14:01
It's the one that installs when I get the package on mint.


![clblas](https://user-images.githubusercontent.com/59298527/233844183-72d47cb9-956f-4955-9be1-33540bffea8f.png)

**Comment by LostRuins** [comment] 2023-04-24 04:04
Okay I guess mint has different package names then. good to know.

**Closed** 2023-04-28 08:03 UTC

**Comment by DaiZaregistriruyus** [comment] 2023-05-12 06:47
@Lordbl4 So did you solve this problem? I have exactly the same CPU, the same amount of RAM and the same problem, I read the thread and didn't really understand if you found a solution. If so, what is it? Thank you!
