### ISSUE TITLE
KoboldCpp v1.36 - I can't use 13B models anymore?

### ISSUE THREAD

**Issue by mrdevolver** [LostRuins/koboldcpp#331] opened 2023-07-21 14:02 UTC
Hello,

it seems like in the current KoboldCpp v1.36, I'm running into the same problem over and over again with any 13B model I run, I always end up with this crash message:

`Processing Prompt [BLAS] (7168 / 7321 tokens)ggml_new_tensor_impl: not enough space in the scratch memory pool (needed 1279262720, available 1197473792)
exception: access violation writing 0x0000000000000050`

Please note that any of the 13B models I tried in previous versions worked without any issues, but just for reference this particular error I posted here happened with Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GGML right now.

In the OS, I can see clearly that there's still some free RAM when this error popped up in the console window, so a message about running out of memory doesn't make much sense to me.

It seems like the only way to fix the problem is to set `--blasbatchsize 512` instead of `--blasbatchsize 1024` which I was using in previous versions with no issues, but 512 is obviously slower, so I'd like to be able to use 1024 again, if possible...

This is my usual chain of parameters which worked previously, but not anymore in the current version:
`koboldcpp.exe --highpriority --threads 4 --blasthreads 4 --contextsize 8192 --smartcontext --stream --blasbatchsize 1024 --useclblast 0 0 --gpulayers 100 --launch`

### Side note:
Before you ask, yes I'm aware that I'm setting `--gpulayers` ridiculously high, but it never seemed to be problem as it was always capped to max. number of layers which is a lower number, so I'm using '100' just to let the program automatically pick the max. number of layers possible.

### My specs:
OS: Windows 10 64bit
CPU: AMD Ryzen 2700x
RAM: 16GB
GPU: AMD Radeon RX Vega 56, 8GB VRAM.

**Comment by LostRuins** [comment] 2023-07-22 09:20
Ah yes, this indeed seems to be a recent regression due to the way the scratch buffers were modified. Thanks for letting me know. I will attempt to fix it.

**Comment by DocShotgun** [comment] 2023-07-22 17:25
> ### My specs:
> OS: Windows 10 64bit CPU: AMD Ryzen 2700x RAM: 16GB GPU: AMD Radeon RX Vega 56, 8GB VRAM.

What size quant are you using? I'm surprised those settings worked at all previously on 13B (I'm also a 16gb ram, 8gb vram user here). I straight up run out of vram on model load if I go above ~32 gpulayers on a 13B q4 quant (this is with previous versions of koboldcpp as well, not just latest). This is also with a lower blas batch size of 256 too, which in theory would use even less vram.

**Comment by mrdevolver** [comment] 2023-07-22 20:28
> > ### My specs:
> > OS: Windows 10 64bit CPU: AMD Ryzen 2700x RAM: 16GB GPU: AMD Radeon RX Vega 56, 8GB VRAM.
> 
> What size quant are you using? I'm surprised those settings worked at all previously on 13B (I'm also a 16gb ram, 8gb vram user here). I straight up run out of vram on model load if I go above ~32 gpulayers on a 13B q4 quant (this is with previous versions of koboldcpp as well, not just latest). This is also with a lower blas batch size of 256 too, which in theory would use even less vram.

Usually I go with Q4_K_M for 13B models, and Q6_K for 7B, but it's not really set in stone for me, it's just that I tried to pick the sweet spot in the middle for testing new quantisers and with smaller models I was more bold, since they aren't that demanding anyway, but I might try different quantisers once this problem is fixed to see what works best for my hardware. If you have similar hardware, it'd be nice if you could do the same, so we could compare our results and see what works best in this hardware tier.

**Comment by mrdevolver** [comment] 2023-07-22 20:30
> Ah yes, this indeed seems to be a recent regression due to the way the scratch buffers were modified. Thanks for letting me know. I will attempt to fix it.

Thank you for looking into it.

**Comment by DocShotgun** [comment] 2023-07-22 22:59
> > > ### My specs:
> > > OS: Windows 10 64bit CPU: AMD Ryzen 2700x RAM: 16GB GPU: AMD Radeon RX Vega 56, 8GB VRAM.
> > 
> > 
> > What size quant are you using? I'm surprised those settings worked at all previously on 13B (I'm also a 16gb ram, 8gb vram user here). I straight up run out of vram on model load if I go above ~32 gpulayers on a 13B q4 quant (this is with previous versions of koboldcpp as well, not just latest). This is also with a lower blas batch size of 256 too, which in theory would use even less vram.
> 
> Usually I go with Q4_K_M for 13B models, and Q6_K for 7B, but it's not really set in stone for me, it's just that I tried to pick the sweet spot in the middle for testing new quantisers and with smaller models I was more bold, since they aren't that demanding anyway, but I might try different quantisers once this problem is fixed to see what works best for my hardware. If you have similar hardware, it'd be nice if you could do the same, so we could compare our results and see what works best in this hardware tier.

Anything greater than ~30-32 gpulayers with 13B q4 exceeds my VRAM. That's why I was wondering how you managed to max out the gpulayers with the same RAM+VRAM as me.

**Comment by mrdevolver** [comment] 2023-07-22 23:15
> > > > ### My specs:
> > > > OS: Windows 10 64bit CPU: AMD Ryzen 2700x RAM: 16GB GPU: AMD Radeon RX Vega 56, 8GB VRAM.
> > > 
> > > 
> > > What size quant are you using? I'm surprised those settings worked at all previously on 13B (I'm also a 16gb ram, 8gb vram user here). I straight up run out of vram on model load if I go above ~32 gpulayers on a 13B q4 quant (this is with previous versions of koboldcpp as well, not just latest). This is also with a lower blas batch size of 256 too, which in theory would use even less vram.
> > 
> > 
> > Usually I go with Q4_K_M for 13B models, and Q6_K for 7B, but it's not really set in stone for me, it's just that I tried to pick the sweet spot in the middle for testing new quantisers and with smaller models I was more bold, since they aren't that demanding anyway, but I might try different quantisers once this problem is fixed to see what works best for my hardware. If you have similar hardware, it'd be nice if you could do the same, so we could compare our results and see what works best in this hardware tier.
> 
> Anything greater than ~30-32 gpulayers with 13B q4 exceeds my VRAM. That's why I was wondering how you managed to max out the gpulayers with the same RAM+VRAM as me.

Perhaps it's not really maxing out and I'm simply misinterpreting it? I don't know. I just thought that setting it to 100 will just fill it as much as possible and won't try to go over the top lol, but maybe it's not really working that way, but it usually says in the console when loading that 41 layers were offloaded or so.

**Comment by Enferlain** [comment] 2023-07-22 23:26
I was getting the same issue but for me it was because I didn't use --contextsize 4096 (thought it got raised by default or something but maybe it was another app or model description)

**Comment by DocShotgun** [comment] 2023-07-23 00:25
> > > > > ### My specs:
> > > > > OS: Windows 10 64bit CPU: AMD Ryzen 2700x RAM: 16GB GPU: AMD Radeon RX Vega 56, 8GB VRAM.
> > > > 
> > > > 
> > > > What size quant are you using? I'm surprised those settings worked at all previously on 13B (I'm also a 16gb ram, 8gb vram user here). I straight up run out of vram on model load if I go above ~32 gpulayers on a 13B q4 quant (this is with previous versions of koboldcpp as well, not just latest). This is also with a lower blas batch size of 256 too, which in theory would use even less vram.
> > > 
> > > 
> > > Usually I go with Q4_K_M for 13B models, and Q6_K for 7B, but it's not really set in stone for me, it's just that I tried to pick the sweet spot in the middle for testing new quantisers and with smaller models I was more bold, since they aren't that demanding anyway, but I might try different quantisers once this problem is fixed to see what works best for my hardware. If you have similar hardware, it'd be nice if you could do the same, so we could compare our results and see what works best in this hardware tier.
> > 
> > 
> > Anything greater than ~30-32 gpulayers with 13B q4 exceeds my VRAM. That's why I was wondering how you managed to max out the gpulayers with the same RAM+VRAM as me.
> 
> Perhaps it's not really maxing out and I'm simply misinterpreting it? I don't know. I just thought that setting it to 100 will just fill it as much as possible and won't try to go over the top lol, but maybe it's not really working that way, but it usually says in the console when loading that 41 layers were offloaded or so.

41 is the max for a 13B model. If I put in 100 gpulayers, it tries to do 41 layers and then immediately crashes. And this is with blas batch size 256, which is even less aggressive than your params lol.

**Comment by mrdevolver** [comment] 2023-07-23 00:49
> > > > > > ### My specs:
> > > > > > OS: Windows 10 64bit CPU: AMD Ryzen 2700x RAM: 16GB GPU: AMD Radeon RX Vega 56, 8GB VRAM.
> > > > > 
> > > > > 
> > > > > What size quant are you using? I'm surprised those settings worked at all previously on 13B (I'm also a 16gb ram, 8gb vram user here). I straight up run out of vram on model load if I go above ~32 gpulayers on a 13B q4 quant (this is with previous versions of koboldcpp as well, not just latest). This is also with a lower blas batch size of 256 too, which in theory would use even less vram.
> > > > 
> > > > 
> > > > Usually I go with Q4_K_M for 13B models, and Q6_K for 7B, but it's not really set in stone for me, it's just that I tried to pick the sweet spot in the middle for testing new quantisers and with smaller models I was more bold, since they aren't that demanding anyway, but I might try different quantisers once this problem is fixed to see what works best for my hardware. If you have similar hardware, it'd be nice if you could do the same, so we could compare our results and see what works best in this hardware tier.
> > > 
> > > 
> > > Anything greater than ~30-32 gpulayers with 13B q4 exceeds my VRAM. That's why I was wondering how you managed to max out the gpulayers with the same RAM+VRAM as me.
> > 
> > 
> > Perhaps it's not really maxing out and I'm simply misinterpreting it? I don't know. I just thought that setting it to 100 will just fill it as much as possible and won't try to go over the top lol, but maybe it's not really working that way, but it usually says in the console when loading that 41 layers were offloaded or so.
> 
> 41 is the max for a 13B model. If I put in 100 gpulayers, it tries to do 41 layers and then immediately crashes. And this is with blas batch size 256, which is even less aggressive than your params lol.

Maybe it's only crashing for you with one specific model? Which model was it? I could test it and see if it will crash for me too.

**Comment by LostRuins** [comment] 2023-07-23 01:50
I can replicate this issue, it seems like the 13b and 7b scratch buffers might be too small for 8k ctx on some models. I am increasing them for the next version

**Comment by LostRuins** [comment] 2023-07-23 02:31
Just getting a feel here: upstream llama.cpp has dropped support for batch sizes over 512 https://github.com/ggerganov/llama.cpp/pull/2325, so I need to know how important it is for koboldcpp to retain blasbatchsize 1024. Do people see any benefit from using 1024 over 512, and is it worth the increased buffer sizes?

**Comment by mrdevolver** [comment] 2023-07-23 04:08
> Just getting a feel here: upstream llama.cpp has dropped support for batch sizes over 512 [ggerganov#2325](https://github.com/ggerganov/llama.cpp/pull/2325), so I need to know how important it is for koboldcpp to retain blasbatchsize 1024. Do people see any benefit from using 1024 over 512, and is it worth the increased buffer sizes?

Heck yes, I've been using 1024 since I discovered it's an option! It increases blas speed for me. If it didn't I wouldn't bother creating this thread and just use 512 instead, but I can feel the speed boost with 1024. In fact, I would go even higher if possible, but higher than 1024 was never an option, so I stayed with 1024.

**Comment by Enferlain** [comment] 2023-07-23 10:06
1024 Is faster than 512

**Comment by LostRuins** [comment] 2023-07-24 03:42
Yeah, I will try to retain support for 1024. 

@NeoTU 2048 was never properly supported, it would segfault randomly, possibly due to incorrect buffer sizes.

**Comment by LostRuins** [comment] 2023-07-24 16:54
Fixed in 1.37, please try

**Comment by mrdevolver** [comment] 2023-07-25 01:57
> Fixed in 1.37, please try

Thank you very much, yes! It seems to work again, yay! 👍

**Comment by bucketcat** [comment] 2023-07-28 22:28
> Just getting a feel here: upstream llama.cpp has dropped support for batch sizes over 512 [ggerganov#2325](https://github.com/ggerganov/llama.cpp/pull/2325), so I need to know how important it is for koboldcpp to retain blasbatchsize 1024. Do people see any benefit from using 1024 over 512, and is it worth the increased buffer sizes?


Without 1024 batch size, using an 8k context model is a completely miserable experience. I personally want 2048, to keep it within a quarter of max context, like how 512 was the default for 2048 token context.

4096 is also going to be important for 16k models. If the context size increases and batches doesn't you end up with a quadratic performance degradation. Not great, no clue what upstream is thinking by removing support. @LostRuins

**Closed** 2023-08-07 07:42 UTC
Labels: bug
