### ISSUE TITLE
[FEATURE] (v1.40.1+) - Add compatibility for GGUF format.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#387] opened 2023-08-17 19:31 UTC
A new format that is intended to be the successor to GGML is nearly ready.  Here is a copy of a summery from Reddit:

>*No more breaking changes.
>*Support for non-llama models. (falcon, rwkv, bloom, etc.)
>*No more fiddling around with rope-freq-base, rope-freq-scale, gqa, and rms-norm-eps.
>*Prompt formats could be set automatically.

Here is a link to documentation that covers the actual workings of the format, and a second link that has a Github discussion on the final testing.

[GGUF format specifications](https://github.com/philpax/ggml/blob/gguf-spec/docs/gguf.md)

[GGUF @ LlamaCPP Github](https://github.com/ggerganov/llama.cpp/pull/2398#issuecomment-1682404719)

**Comment by LostRuins** [comment] 2023-08-18 03:25
Yes I am aware, and will apply necessary changes when it is merged

**Comment by SabinStargem** [comment] 2023-08-18 05:08
I am looking forward to it.  ROPE is so very finicky, being able to just plug a model into Kobold will be good.   Thanks for the effort.  :)

**Comment by msub2** [comment] 2023-08-22 17:51
Merged as of yesterday: https://github.com/ggerganov/llama.cpp/pull/2398#issuecomment-1686986770

**Comment by LostRuins** [comment] 2023-08-23 01:25
working on it

**Comment by LostRuins** [comment] 2023-08-23 14:26
I've got it working for llama in my experimental branch, but haven't tested cuda yet. It looks like the GGUF for other architectures will have to wait though.

**Comment by jacob1218** [comment] 2023-08-23 19:04
support for falcon coming shortly: https://github.com/ggerganov/llama.cpp/pull/2717#issuecomment-1690472639

**Comment by jacob1218** [comment] 2023-08-23 22:49
was merged upstream
idk if any other architectures are supported right now (GPT-NeoX has a WIP implementation according to this https://github.com/ggerganov/llama.cpp/issues/2706#issuecomment-1687907590)

**Comment by mirek190** [comment] 2023-08-23 23:15
falcon and Neon-X are connected ...

**Comment by LostRuins** [comment] 2023-08-24 14:02
GGUF for llama models has been merged in the latest (v1.41) release

**Comment by digiwombat** [comment] 2023-08-24 14:16
Hopping in with SUPER early CUDA testing against TheBloke/PuddleJumper-13B-GGUF  (caveat, I have not tested against llama.cpp native, so these may be shared problems).

Settings are standard LLaMa2 load settings. 7 CPU threads, 40 GPU layers, 512 batch, no linear rope, unbanned tokens, cublas enabled.

Speeds across the board are way down for GGUF. Loading of models is incredibly slow and GPU heavy. Prompt processing is glacial. I am still processing the initial 1747 token prompt about 10 minutes after hitting enter. Will edit this post with generation times once it finishes.

**Comment by LostRuins** [comment] 2023-08-24 14:22
Really? I experienced the opposite, I am getting faster speeds than before. I suspect it may not be related to GGUF, but rather now I have set MMQ to default. Can you try toggle it and compare?

**Comment by digiwombat** [comment] 2023-08-24 14:24
Might be. I'll double check MMQ settings. I don't think I've updated my settings file in a while.

**Comment by digiwombat** [comment] 2023-08-24 14:44
All models below are q5_K_M, run on a 3080Ti, MMQ Off.

Second run with MMQ confirmed disabled, model load was faster, but still fairly slow, might have hit cache or something:  
![image](https://github.com/LostRuins/koboldcpp/assets/58859/b24439cd-315e-4a6c-949f-cd88dd237479)

ggjtv3 cuBLAS in 1.41 (Beta), very slow model load:
Stopped after 3 minutes and still on 512/1747 prompt processing
ggjtv3 cuBLAS in 1.40.1 is similar.

clBLAS on 1.41 (Beta), normal model load speed:
![image](https://github.com/LostRuins/koboldcpp/assets/58859/91172ca2-057e-42aa-b729-42cbe8ecb133)

So yeah, something has gone wonky with cuBLAS. I am assuming koboldcpp uses the embedded CUDA dll by default. I don't have a system without cuBLAS installed at the moment so I can't test if that's somehow causing an issue.

**Comment by digiwombat** [comment] 2023-08-24 14:54
I edited my comment for any e-mail lurkers. It seems like it was a GPU hiccup, not a problem with gens/koboldcpp/cublas. It did last through multiple program restarts, but apologies for the alarm.

**Comment by LostRuins** [comment] 2023-08-25 05:07
Good to hear it's working as expected

**Closed** 2023-08-30 18:36 UTC
