### ISSUE TITLE
Performance loss on the last release. 

### ISSUE THREAD

**Issue by Barafu** [LostRuins/koboldcpp#458] opened 2023-10-01 20:05 UTC
# Problem 
I downloaded the latest release and got performace loss. The exactly same command that I used before now generates at ~580 ms/T when before that is used to be ~440 ms/T.  The prompt ingestion speed also changed from pretty stable 21ms/T to 23ms/T. 
As an additional confirmation, the annoying squeaky sound from my GPU when generating has changed tone significantly. 

# Hardware
GTX4090, latest drivers 537
Ryzen 9 3950X
64GB RAM

# Software
Windows 11. 
` .\koboldcpp.exe --version
Welcome to KoboldCpp - Version 1.45`

The exact command is `.\koboldcpp.exe --model .\xwin-lm-70b-v0.1.Q3_K_M.gguf --usecublas --gpulayers 48 --stream --contextsize 4096`

Please tell if there are any tests I can do to help.

**Comment by Z95070** [comment] 2023-10-02 03:29
Seconding, though with even worse regression; 70B went from 850ms /t to 2100ms /t or so.

Quadro P5000
Xeon 2175
128GB RAM
Win 10 LTSC

**Comment by fenixlam** [comment] 2023-10-02 04:42
I am a CPU user, and i always play it in threads 12. I noticed that 1.45 exe runs with only 4 threads, although it looks like it didn't affect the performance... how to generate report just like the first floor did?

**Comment by LostRuins** [comment] 2023-10-02 04:49
Hi all, sorry for this issue, the thread counts were not being set properly. Please try 1.45.2 and it should be fixed. Thanks!

**Comment by Barafu** [comment] 2023-10-02 08:32
Yes, it works again. Thank you for fixing!

**Comment by KiraSlith** [comment] 2023-10-12 04:24
Thirding, there's definitely been performance degradation. CPU and GPU aren't throttling, I've already checked. The releases after 1.44.2 are doing a LOT more copy operations during BLAS processing according to Windows. Math ops on Ryzen Mobile APUs bottleneck between threads, so I only use 6 threads, which Windows' scheduler assigns individually to the 6 physical cores.

I just finished a round of A-B testing between 1.44.2, 1.45.2, and 1.46.1.  On the exact same 2872 token prompt, 1.44.2 gets it done in 163.9s, 1.45.2 gets it done in 345.7s, 1.46.1 gets it done in 404.5s. A second round before switching showed performance within the same ballpark.
Options used on all 3: `koboldcpp-[VersionNumber].exe --usecublas lowvram --gpulayers 17 --highpriority --threads 6 --skiplauncher --contextsize 3072 --threads 6 stheno-l2-13b.Q6_K.gguf`

Ryzen 5 4600H (Update Revision 0401600800000000, no I don't know what AGESA version that matches)
32gb DDR4 3200mhz
1660ti 6gb "Max-Q" Drv: 528.33
Windows 10 "ReviOS" Ver: 22.12

**Comment by LostRuins** [comment] 2023-10-12 16:05
Did you update your nvidia drivers recently? Those timings are very slow for a 1660ti. A lot has changed upstream and I'm not sure exactly which part is causing you problems. I'd advise trying the following

1. Try running with MMQ. `--usecublas mmq`
2. Try running with slightly fewer thread and gpulayers. `--gpulayers 15 --threads 5`
3. Try disabling highpriority.
4. If the above all fails, try comparing against clblast timings.

**Comment by KiraSlith** [comment] 2023-10-12 20:57
It's the "High Performance" Notebook PC version of the 1660ti, so the worse performance vs desktop is expected, but the huge leap in calculation times between KoboldCPP versions is not. I'm not going to test 1.45.2, instead skipping straight to 1.46.1 since the performance loss was already in the same ballpark between the two. If I got an unusually short response I moved on and came back later to regenerate, as to minimize variable impact between generations.

A-B Testing again, 2872 token test load, repeated by cycling the same 3 phrasings between each to prevent CuBLAS recycling and reduce variables, starting from the settings I provided in my last response.

Upgraded to Nvidia Driver 537.58; 
1.44.2: 134.6s, 122.3s, 135.4s
1.46.1: 255.8s, 259.4s, 221.5s

(Mid-testing notes: Looks like the driver version had some impact. It does look like the CPU is carrying a lot more load than the GPU during the BLAS cycle on 1.46.1, combined with the copy spam I'm inclined to believe you're right, there's a downstream package misbehaving in the latest release, but I wouldn't know how to test which package is doing that though...)

Switched to MMQ:
1.44.2: 128.1s, 113.1s, 117.1s
1.46.1: 119.1s, 124.5s, 135.5s 
(Mid-testing notes: Last time I tested MMQ was 1.40.1 and it didn't seem to change performance at all and it doesn't seem to have had much impact on 1.44.2 either, but it nearly closed the gap between versions. I didn't really expect that, but it is a pleasant surprise. It also seems to have balanced out the load behavior of the CPU and GPU with a lot fewer "copy" operations, how does that make any sense?)

1 Fewer threads and layers and MMQ:
1.44.2: 118.5s, 114.8s, 103.2s
1.46.1: 142.6s, 118.1s, 111.8s
(Mid-testing notes: It seemed to improve performance on 1.44.2, but on 1.46.1 it's a mixed bag. I think for now I'm going to put it in between leave it at 16 layers and 6 threads.)

MMQ, 16 layers, 6 threads, `--highpriority` off.
1.44.2: 104.6s, 102.2s, 101.9s
1.46.1:  89.0s, 129.3s, 89.8s
(Mid-testing notes: I didn't expect high priority to have a negative impact on performance, usually getting priority pushes a task up to the front of the cue, giving it the best chance to run as fast as possible. The odd spike on 1.46.1 is a little off-putting though.)

I'll try testing clBLAS another time.

I wouldn't call it "resolved", there definitely shouldn't have been such a large performance drop just moving versions with the same config, but it is way better than it started out.

**Comment by LostRuins** [comment] 2023-10-13 01:55
So without getting too technical, there are some pitfalls with Nvidia that could lead to this behavior. One is FP16 support when using CuBLAS - which has been added relatively recently and is usually faster - on new cards. However on old cards FP16 can actually be SLOWER than FP32. Likewise, using too many layers can lead to newer drivers quietly offloading to shared memory instead when dedicated VRAM is consumed which will lead to a slowdown. Highpriority can lead to slowdowns too on some systems. That's why I recommend tweaking around settings to find the optimal setup for you - there is no magic bullet.

Anyway, glad you got it to be faster now. Hope this helps others in future.

**Comment by KiraSlith** [comment] 2023-10-13 02:32
Okay. None of those were an issue beforehand though. The severe performance degradation with identicate settings only set in after the version change, why would it be trying to use FP16 when the input model is a 6bit GGUF, just up cast to 32bit like normal and go.

**Comment by LostRuins** [comment] 2023-10-14 01:51
FP16 cublas matmul is faster on supported cards, and that's what they did upstream.

**Closed** 2023-10-22 10:52 UTC
Labels: bug
