### ISSUE TITLE
Runpod template is broken

### ISSUE THREAD

**Issue by christiandaley** [LostRuins/koboldcpp#1199] opened 2024-11-04 16:08 UTC
When spinning up the latest koboldcpp Runpod template the container logs show the following error:

![image](https://github.com/user-attachments/assets/d9c1597b-c681-4fbe-88d8-227067b37d2b)

**Comment by LostRuins** [comment] 2024-11-05 11:43
Tagging @henk717

**Comment by henk717** [comment] 2024-11-05 12:30
I have run it succesfully both yesterday and today so I can't reproduce this. Please double check you are using https://koboldai.org/runpodcpp our official template. Also make sure to not manually include the parameter that would show the model selecrion dialogue. The error shown can only happen if it feels the need to show the model selection dialogue which is not possible if the model was specified without manually adding the parameter for the dialogue.

**Comment by LostRuins** [comment] 2024-12-01 05:47
Closing as resolved, please reopen if you still have issues with runpod

**Closed as completed by LostRuins** 2024-12-01 05:47 UTC
