### ISSUE TITLE
Possible bug in the koboldcpp colab (Vision clip issue)

### ISSUE THREAD

**Issue by yoshuzx** [LostRuins/koboldcpp#797] opened 2024-04-21 10:42 UTC
There may be a bug in the koboldcpp colab. I tried using a vision model like Llava 7B, but when I load one image, the processing is really slow. I noticed that the clip is being loaded on the CPU instead of CUDA by default.  Is there a way to change or fix this? Thank you in advance.

**Comment by LostRuins** [comment] 2024-04-22 15:01
I can confirm there is a speed regression between 1.61.2 and 1.62

**Comment by LostRuins** [comment] 2024-04-23 12:02
I have narrowed it down to the backend changes between 073a279(18 mar) and 8131616 (20 mar), it seems to be somehow initializing cuda in a different order. Unfortunately I ran out of colab usage so I will have to resume testing another day.

If anyone is able to, you can try running the current experimental branch and see if it still has issues. I've made a few fix changes but cannot test them.

**Comment by LostRuins** [comment] 2024-05-01 14:19
Hi, Should be fixed in the latest version, please try.

**Closed as completed** 2024-08-19 08:58 UTC
Labels: bug
